#!/usr/bin/env node
/**
 * sync-shared — provision the teacher repo from this (student) repo, which is
 * the single source of truth.
 *
 * Why this repo is canonical: it already owns the backend source of truth
 * (apps-script.js + tests/), so the shared frontend files (config/api/utils/
 * i18n/call-request + theme/mobile CSS) live here too and every HTML page
 * references them at their normal src/ paths. The teacher repo holds only its
 * teacher-specific pages/scripts plus generated artifacts kept in lockstep by
 * this script (run locally via `npm run sync`, or in CI on push to master).
 *
 * What it writes into the teacher repo:
 *   - Verbatim copies of the shared files (same relative paths).
 *   - A teacher-scoped sw.js, generated from this repo's sw.js by swapping the
 *     app-shell list + cache version (so the offline logic never drifts).
 *   - The teacher CNAME (teacher.fluentpath.ca).
 *
 * Usage:
 *   node scripts/sync-shared.mjs [--dest=<teacher-repo-root>] [--check] [--list]
 *     --dest=<path>  Teacher repo root. Defaults to $TEACHER_REPO, else
 *                    ../fluentpath-teacher (sibling checkout).
 *     --check        Don't write — exit 1 if the dest is out of sync (CI guard).
 *     --list         Print the managed output paths and exit.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { resolve, dirname, join } from 'path';

const ROOT = resolve(import.meta.dirname, '..');

// Verbatim shared files. Edit these in THIS repo only; the teacher repo's
// copies are regenerated from here.
const SHARED_FILES = [
  'src/scripts/config.js',
  'src/scripts/api.js',
  'src/scripts/utils.js',
  'src/scripts/i18n.js',
  'src/scripts/call-request.js',
  'src/scripts/password-reset.js',
  'src/styles/theme.css',
  'src/styles/mobile.css',
  'favicon.svg',
];

// Teacher service worker (generated from this repo's sw.js).
const TEACHER_CACHE_VERSION = 'fp-teacher-v4'; // bump to evict old caches
const TEACHER_APP_SHELL = [
  './',
  './index.html',
  './teacher.html',
  './favicon.svg',
  './src/examiner-panel.html',
  './src/scripts/config.js',
  './src/scripts/api.js',
  './src/scripts/utils.js',
  './src/scripts/teacher-portal.js',
  './src/scripts/examiner-panel.js',
  './src/scripts/call-request.js',
  './src/scripts/i18n.js',
  './src/scripts/password-reset.js',
  './src/styles/theme.css',
  './src/styles/mobile.css',
  './src/styles/teacher-portal.css',
  './src/styles/examiner-panel.css',
];

const TEACHER_CNAME = 'teacher.fluentpath.ca\n';

/** Derive the teacher service worker from the student sw.js (logic shared). */
function teacherServiceWorker(studentSw) {
  const shell = TEACHER_APP_SHELL.map((p) => `  '${p}',`).join('\n');
  return studentSw
    .replace(/var CACHE_VERSION = '[^']*';[^\n]*/,
      `var CACHE_VERSION = '${TEACHER_CACHE_VERSION}'; // teacher repo — generated by scripts/sync-shared.mjs`)
    .replace('STUDENT-scoped: only the student site',
      'TEACHER-scoped (generated): only the teacher dashboard')
    .replace(/var APP_SHELL = \[[\s\S]*?\];/, `var APP_SHELL = [\n${shell}\n];`);
}

/** The full set of outputs the teacher repo should contain, as {rel, content}. */
function buildOutputs() {
  const outputs = [];
  for (const rel of SHARED_FILES) {
    const srcPath = resolve(ROOT, rel);
    if (!existsSync(srcPath)) {
      console.error(`[sync-shared] Missing source file: ${rel}`);
      process.exit(2);
    }
    outputs.push({ rel, content: readFileSync(srcPath, 'utf-8') });
  }
  outputs.push({ rel: 'sw.js', content: teacherServiceWorker(readFileSync(resolve(ROOT, 'sw.js'), 'utf-8')) });
  outputs.push({ rel: 'CNAME', content: TEACHER_CNAME });
  return outputs;
}

function parseArgs(argv) {
  const args = { dest: process.env.TEACHER_REPO || '../fluentpath-teacher', check: false, list: false };
  for (const a of argv) {
    if (a === '--check') args.check = true;
    else if (a === '--list') args.list = true;
    else if (a.startsWith('--dest=')) args.dest = a.slice('--dest='.length);
  }
  return args;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const outputs = buildOutputs();

  if (args.list) {
    console.log(outputs.map((o) => o.rel).join('\n'));
    return;
  }

  const dest = resolve(ROOT, args.dest);
  if (!existsSync(dest)) {
    console.error(`[sync-shared] Destination not found: ${dest}\n` +
      `Point --dest or $TEACHER_REPO at the teacher repo checkout.`);
    process.exit(2);
  }

  let drift = 0;
  let written = 0;
  for (const { rel, content } of outputs) {
    const destPath = join(dest, rel);
    const current = existsSync(destPath) ? readFileSync(destPath, 'utf-8') : null;
    if (current === content) continue;

    if (args.check) {
      console.error(`[sync-shared] OUT OF SYNC: ${rel}`);
      drift++;
    } else {
      mkdirSync(dirname(destPath), { recursive: true });
      writeFileSync(destPath, content);
      console.log(`[sync-shared] wrote ${rel}`);
      written++;
    }
  }

  if (args.check) {
    if (drift > 0) {
      console.error(`[sync-shared] ${drift} file(s) out of sync. Run \`npm run sync\` and commit.`);
      process.exit(1);
    }
    console.log('[sync-shared] teacher repo is in sync.');
  } else {
    console.log(`[sync-shared] done — ${written} updated, ${outputs.length - written} already current.`);
  }
}

main();
